ignored = ["github.com/spf13/cobra"]

[[constraint]]
  branch = "master"
  name = "github.com/ftrvxmtrx/fd"

[[constraint]]
  branch = "master"
  name = "github.com/problame/go-rwccmd"

[[constraint]]
  name = "github.com/theckman/goconstraint"
  version = "1.11.0"
